### ISSUE TITLE
统一全书中的专有名词翻译

### ISSUE THREAD

**Issue by rootsongjc** [servicemesher/getting-started-with-knative#28]
该 Issue 用于统一全书中的专有名词翻译，需要统一的名字请在回复中列出。

**Comment by junahan** [comment]
Serving 服务
Service 服务
Revision 修订版本
Route 路由
Configuration 配置
Autoscaler 自动伸缩器
Activator 激活器
Reserve 待命，保留
Panic Mode 忙碌模式
Stable Mode 稳定模式

**Comment by haiker2011** [comment]
我们经常使用 `kubectl apply -f` ，请问 `apply` 翻译为哪个单词比较恰当？

**Comment by junahan** [comment]
像是 kubectl apply -f ，作为命令的一个整体，apply 应当无需翻译。

**Comment by haiker2011** [comment]
有时候是在文章中单独出现，这个时候感觉不翻译有点怪怪的。

**Comment by rootsongjc** [comment]
本书以重新整理和发布了，关闭该 issue。
