### ISSUE TITLE
失效链接

### ISSUE THREAD

**Issue by chengwhynot** [servicemesher/getting-started-with-knative#37]
这个链接在github里面正常，但是在website上点了只见到地址栏切换，内容没变。
![bad-link](https://user-images.githubusercontent.com/1076902/58685631-fd603680-83ae-11e9-8a15-1689728e4914.PNG)

**Comment by chengwhynot** [comment]
在这个页面的最下面 http://www.servicemesher.com/getting-started-with-knative/

**Comment by rootsongjc** [comment]
@chengwhynot 麻烦直接提交 PR 修改下吧

**Comment by chengwhynot** [comment]
两种改法：
1. 直接给成 GitHub的硬链接（https://github.com/servicemesher/getting-started-with-knative/blob/master/CODE_OF_CONDUCT.md）
pros:
  简单粗暴直接
cons:
  硬链接比较丑陋

2. 把这篇规范也添加到README.md，然后还是相对路径
pros:
  看起来不是硬编码
cons:
  会出现在书左侧的目录中（不过这也不一定是坏事？）

---
你倾向于哪一种？

**Comment by chengwhynot** [comment]
用了第一种，感觉放在左边的目录里不合适
